name: classpulse_app
description: Flutter client for the ClassPulse automated attendance system.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_blue_plus: ^1.31.15
  flutter_secure_storage: ^9.2.1
  firebase_core: ^3.5.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.2.4
  firebase_remote_config: ^5.0.5
  geolocator: ^12.0.0
  http: ^1.2.2
  network_info_plus: ^5.0.2
  permission_handler: ^11.3.0
  file_picker: ^8.0.6
  path: ^1.9.0
  uuid: ^4.4.0
  lottie: ^3.1.2
  shimmer: ^3.0.0
  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
